# Generated by Django 3.2.7 on 2021-09-27 10:47

from django.db import migrations, models
import djongo.models.fields
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCache',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=30)),
                ('merchantId', models.CharField(max_length=30)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('data', djongo.models.fields.EmbeddedField(model_container=transaction.models.TransactionData, model_form_class=transaction.models.TransactionForm)),
            ],
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-createdAt',)},
        ),
    ]
